import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Todo Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	const btnStyle =
		'px-6 py-2 rounded-md text-stone-50 bg-stone-950 hover:bg-stone-600 focus-visible:bg-stone-600 outline-stone-600 duration-200';

	return (
		<html lang='en'>
			<body
				className={inter.className + ' min-h-svh p-4 flex flex-col gap-y-4'}>
				<nav className='p-4 flex flex-wrap gap-x-4'>
					<Link className={btnStyle} href={'/'}>
						Home page
					</Link>
					<Link className={btnStyle} href={'/todo'}>
						To do
					</Link>
				</nav>

				{children}
			</body>
		</html>
	);
}
